rootLogger.level = warn
rootLogger.appenderRef.stdout.ref = console

appender.console.type = Console
appender.console.name = console
appender.console.target = SYSTEM_ERR
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yy/MM/dd HH:mm:ss} %p %c{1}: %m%n

# Specifically mute Apache Spark internal logs
logger.spark.name = org.apache.spark
logger.spark.level = warn

# Specifically mute Hadoop internal logs
logger.hadoop.name = org.apache.hadoop
logger.hadoop.level = warn


logger.mycode.name = com.example.spark
logger.mycode.level = info